#!/bin/sh

DAEMON_USER="dtnd"

case "$1" in
  configure)
	#Creating the user if it does not exist
	if (id dtnd);then
	echo "user exists";
	else 	
	adduser --system ${DAEMON_USER};
	fi
	;;
	
  abort-upgrade)
	;;
	
  abort-remove)
	;;
	
  abort-deconfigure)
	;;
	
  *)
	echo "$0: didn't understand being called with \`$1'" 1>&2
	exit 0
	;;
esac

exit 0
