#!/bin/sh

DAEMON_USER="dtnd"

case "$1" in
  configure)
	#Creating the user if it does not exist
	adduser --ingroup daemon --system ${DAEMON_USER};
        if [ ! -d "/var/log/ibrdtn" ]; then
          mkdir -p /var/log/ibrdtn
          chown dtnd.adm /var/log/ibrdtn
          chmod 775 /var/log/ibrdtn
        fi
	;;
	
  abort-upgrade)
	;;
	
  abort-remove)
	;;
	
  abort-deconfigure)
	;;
	
  *)
	echo "$0: didn't understand being called with \`$1'" 1>&2
	exit 0
	;;
esac

exit 0
