#!/bin/sh

DAEMON_USER="dtnd"

case "$1" in
  configure)
	# Creating the user if it does not exist
	adduser --ingroup daemon --system ${DAEMON_USER};
	
	# create a log directory for the daemon process
	LOG_DIR="/var/log/ibrdtn"
	if [ ! -d "${LOG_DIR}" ]; then
		mkdir -p ${LOG_DIR}
		chown dtnd.adm ${LOG_DIR}
		chmod 775 ${LOG_DIR}
	fi
	
	# create a pid directory for the daemon process
	PID_DIR="/var/run/ibrdtn"
	if [ ! -d "${PID_DIR}" ]; then
		mkdir -p ${PID_DIR}
		chown dtnd.adm ${PID_DIR}
		chmod 775 ${PID_DIR}
	fi
	;;
	
  abort-upgrade)
	;;
	
  abort-remove)
	;;
	
  abort-deconfigure)
	;;
	
  *)
	echo "$0: didn't understand being called with \`$1'" 1>&2
	exit 0
	;;
esac

exit 0
