#!/bin/bash
#
# This script makes cross-compiling very easy. Follow these three steps:
#
# 1: ./cross <DEST-ARCH> <LOCAL-ARCH>
#    e.g. ./cross arm-linux-gnu i686-linux-gnu
# 2: ./cross configure
# 3: ./cross compile
#

# get architecture
if [ -e ".cross-arch" ]; then
	ARCH=`cat .cross-arch`
fi

if [ -e ".cross-host" ]; then
	HOST=`cat .cross-host`
fi

# create parameters
export AR="$ARCH-ar"
export AS="$ARCH-gcc"
export LD="$ARCH-ld"
export NM="$ARCH-nm"
export CC="$ARCH-gcc"
export GCC="$ARCH-gcc"
export CXX="$ARCH-g++"
export RANLIB="$ARCH-ranlib"
export STRIP="$ARCH-strip"
export OBJCOPY="$ARCH-objcopy"
export OBJDUMP="$ARCH-objdump"
export CPPFLAGS="-I/usr/$ARCH/include/c++"
export CC="$ARCH-gcc"
export CXX="$ARCH-g++"

if [ "$1" == "compile" ]; then
	make
elif [ "$1" == "configure" ]; then
	export ac_cv_func_malloc_0_nonnull=yes
	./configure --target=$ARCH --host=$ARCH --build=$HOST
else
	echo "$1" > .cross-arch
	echo "$2" > .cross-host
fi

