/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_swig_WRAP_H_
#define SWIG_swig_WRAP_H_

class SwigDirector_NativeSessionCallback : public dtn::api::NativeSessionCallback, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_NativeSessionCallback(JNIEnv *jenv);
    virtual ~SwigDirector_NativeSessionCallback();
    virtual void notifyBundle(dtn::data::BundleID const &id) throw();
    virtual void notifyStatusReport(dtn::data::StatusReportBlock const &report) throw();
    virtual void notifyCustodySignal(dtn::data::CustodySignalBlock const &custody) throw();
public:
    bool swig_overrides(int n) {
      return (n < 3 ? swig_override[n] : false);
    }
protected:
    bool swig_override[3];
};


#endif
