/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.tubs.ibr.dtn.swig;

public class AdministrativeBlock {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AdministrativeBlock(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AdministrativeBlock obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigJNI.delete_AdministrativeBlock(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean refsFragment() {
    return swigJNI.AdministrativeBlock_refsFragment(swigCPtr, this);
  }

  public void read(SWIGTYPE_p_dtn__data__PayloadBlock p) {
    swigJNI.AdministrativeBlock_read(swigCPtr, this, SWIGTYPE_p_dtn__data__PayloadBlock.getCPtr(p));
  }

  public void write(SWIGTYPE_p_dtn__data__PayloadBlock p) {
    swigJNI.AdministrativeBlock_write(swigCPtr, this, SWIGTYPE_p_dtn__data__PayloadBlock.getCPtr(p));
  }

  public void set_admfield(char value) {
    swigJNI.AdministrativeBlock__admfield_set(swigCPtr, this, value);
  }

  public char get_admfield() {
    return swigJNI.AdministrativeBlock__admfield_get(swigCPtr, this);
  }

}
