/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.tubs.ibr.dtn.swig;

public class BundleNotFoundException {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BundleNotFoundException(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BundleNotFoundException obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigJNI.delete_BundleNotFoundException(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BundleNotFoundException(String what) {
    this(swigJNI.new_BundleNotFoundException__SWIG_0(what), true);
  }

  public BundleNotFoundException() {
    this(swigJNI.new_BundleNotFoundException__SWIG_1(), true);
  }

}
