/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.tubs.ibr.dtn.swig;

public class Bundle {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Bundle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Bundle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigJNI.delete_Bundle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Bundle() {
    this(swigJNI.new_Bundle(), true);
  }

  public SWIGTYPE_p_std__listT_refcnt_ptrT_Block_t_t getBlocks() {
    return new SWIGTYPE_p_std__listT_refcnt_ptrT_Block_t_t(swigJNI.Bundle_getBlocks(swigCPtr, this), false);
  }

  public SWIGTYPE_p_dtn__data__Block getBlock(int index) {
    return new SWIGTYPE_p_dtn__data__Block(swigJNI.Bundle_getBlock__SWIG_0(swigCPtr, this, index), false);
  }

  public SWIGTYPE_p_dtn__data__PayloadBlock push_front(SWIGTYPE_p_ibrcommon__BLOB__Reference ref) {
    return new SWIGTYPE_p_dtn__data__PayloadBlock(swigJNI.Bundle_push_front__SWIG_1(swigCPtr, this, SWIGTYPE_p_ibrcommon__BLOB__Reference.getCPtr(ref)), false);
  }

  public SWIGTYPE_p_dtn__data__PayloadBlock push_back(SWIGTYPE_p_ibrcommon__BLOB__Reference ref) {
    return new SWIGTYPE_p_dtn__data__PayloadBlock(swigJNI.Bundle_push_back__SWIG_1(swigCPtr, this, SWIGTYPE_p_ibrcommon__BLOB__Reference.getCPtr(ref)), false);
  }

  public SWIGTYPE_p_dtn__data__PayloadBlock insert(SWIGTYPE_p_dtn__data__Block before, SWIGTYPE_p_ibrcommon__BLOB__Reference ref) {
    return new SWIGTYPE_p_dtn__data__PayloadBlock(swigJNI.Bundle_insert__SWIG_1(swigCPtr, this, SWIGTYPE_p_dtn__data__Block.getCPtr(before), SWIGTYPE_p_ibrcommon__BLOB__Reference.getCPtr(ref)), false);
  }

  public SWIGTYPE_p_dtn__data__Block push_front(SWIGTYPE_p_dtn__data__ExtensionBlock__Factory factory) {
    return new SWIGTYPE_p_dtn__data__Block(swigJNI.Bundle_push_front__SWIG_2(swigCPtr, this, SWIGTYPE_p_dtn__data__ExtensionBlock__Factory.getCPtr(factory)), false);
  }

  public SWIGTYPE_p_dtn__data__Block push_back(SWIGTYPE_p_dtn__data__ExtensionBlock__Factory factory) {
    return new SWIGTYPE_p_dtn__data__Block(swigJNI.Bundle_push_back__SWIG_2(swigCPtr, this, SWIGTYPE_p_dtn__data__ExtensionBlock__Factory.getCPtr(factory)), false);
  }

  public SWIGTYPE_p_dtn__data__Block insert(SWIGTYPE_p_dtn__data__ExtensionBlock__Factory factory, SWIGTYPE_p_dtn__data__Block before) {
    return new SWIGTYPE_p_dtn__data__Block(swigJNI.Bundle_insert__SWIG_2(swigCPtr, this, SWIGTYPE_p_dtn__data__ExtensionBlock__Factory.getCPtr(factory), SWIGTYPE_p_dtn__data__Block.getCPtr(before)), false);
  }

  public void remove(SWIGTYPE_p_dtn__data__Block block) {
    swigJNI.Bundle_remove(swigCPtr, this, SWIGTYPE_p_dtn__data__Block.getCPtr(block));
  }

  public void clearBlocks() {
    swigJNI.Bundle_clearBlocks(swigCPtr, this);
  }

  public String toString() {
    return swigJNI.Bundle_toString(swigCPtr, this);
  }

  public long blockCount() {
    return swigJNI.Bundle_blockCount(swigCPtr, this);
  }

  public boolean allEIDsInCBHE() {
    return swigJNI.Bundle_allEIDsInCBHE(swigCPtr, this);
  }

}
