/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.tubs.ibr.dtn.swig;

public class BundleID {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BundleID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BundleID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigJNI.delete_BundleID(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BundleID(EID source, long timestamp, long sequencenumber, boolean fragment, long offset) {
    this(swigJNI.new_BundleID__SWIG_0(EID.getCPtr(source), source, timestamp, sequencenumber, fragment, offset), true);
  }

  public BundleID(EID source, long timestamp, long sequencenumber, boolean fragment) {
    this(swigJNI.new_BundleID__SWIG_1(EID.getCPtr(source), source, timestamp, sequencenumber, fragment), true);
  }

  public BundleID(EID source, long timestamp, long sequencenumber) {
    this(swigJNI.new_BundleID__SWIG_2(EID.getCPtr(source), source, timestamp, sequencenumber), true);
  }

  public BundleID(EID source, long timestamp) {
    this(swigJNI.new_BundleID__SWIG_3(EID.getCPtr(source), source, timestamp), true);
  }

  public BundleID(EID source) {
    this(swigJNI.new_BundleID__SWIG_4(EID.getCPtr(source), source), true);
  }

  public BundleID() {
    this(swigJNI.new_BundleID__SWIG_5(), true);
  }

  public BundleID(Bundle b) {
    this(swigJNI.new_BundleID__SWIG_6(Bundle.getCPtr(b), b), true);
  }

  public String toString() {
    return swigJNI.BundleID_toString(swigCPtr, this);
  }

  public long getTimestamp() {
    return swigJNI.BundleID_getTimestamp(swigCPtr, this);
  }

  public void setSource(EID value) {
    swigJNI.BundleID_source_set(swigCPtr, this, EID.getCPtr(value), value);
  }

  public EID getSource() {
    long cPtr = swigJNI.BundleID_source_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EID(cPtr, false);
  }

  public void setTimestamp(long value) {
    swigJNI.BundleID_timestamp_set(swigCPtr, this, value);
  }

//  public long getTimestamp() {
//    return swigJNI.BundleID_timestamp_get(swigCPtr, this);
//  }

  public void setSequencenumber(long value) {
    swigJNI.BundleID_sequencenumber_set(swigCPtr, this, value);
  }

  public long getSequencenumber() {
    return swigJNI.BundleID_sequencenumber_get(swigCPtr, this);
  }

  public void setFragment(boolean value) {
    swigJNI.BundleID_fragment_set(swigCPtr, this, value);
  }

  public boolean getFragment() {
    return swigJNI.BundleID_fragment_get(swigCPtr, this);
  }

  public void setOffset(long value) {
    swigJNI.BundleID_offset_set(swigCPtr, this, value);
  }

  public long getOffset() {
    return swigJNI.BundleID_offset_get(swigCPtr, this);
  }

}
