/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.tubs.ibr.dtn.swig;

public class DTNTime {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DTNTime(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DTNTime obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigJNI.delete_DTNTime(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DTNTime() {
    this(swigJNI.new_DTNTime__SWIG_0(), true);
  }

  public DTNTime(long seconds, long nanoseconds) {
    this(swigJNI.new_DTNTime__SWIG_1(seconds, nanoseconds), true);
  }

  public DTNTime(long seconds) {
    this(swigJNI.new_DTNTime__SWIG_2(seconds), true);
  }

  public DTNTime(SDNV seconds, SDNV nanoseconds) {
    this(swigJNI.new_DTNTime__SWIG_3(SDNV.getCPtr(seconds), seconds, SDNV.getCPtr(nanoseconds), nanoseconds), true);
  }

  public SDNV getTimestamp() {
    return new SDNV(swigJNI.DTNTime_getTimestamp(swigCPtr, this), false);
  }

  public SDNV getNanoseconds() {
    return new SDNV(swigJNI.DTNTime_getNanoseconds(swigCPtr, this), false);
  }

  public void set() {
    swigJNI.DTNTime_set(swigCPtr, this);
  }

  public long getLength() {
    return swigJNI.DTNTime_getLength(swigCPtr, this);
  }

}
