/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.tubs.ibr.dtn.swig;

public class EID {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigJNI.delete_EID(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static String getDEFAULT_SCHEME() {
    return swigJNI.EID_DEFAULT_SCHEME_get();
  }

  public static String getCBHE_SCHEME() {
    return swigJNI.EID_CBHE_SCHEME_get();
  }

  public EID() {
    this(swigJNI.new_EID__SWIG_0(), true);
  }

  public EID(String scheme, String ssp) {
    this(swigJNI.new_EID__SWIG_1(scheme, ssp), true);
  }

  public EID(String value) {
    this(swigJNI.new_EID__SWIG_2(value), true);
  }

  public EID(long node, long application) {
    this(swigJNI.new_EID__SWIG_3(node, application), true);
  }

  public boolean sameHost(String other) {
    return swigJNI.EID_sameHost__SWIG_0(swigCPtr, this, other);
  }

  public boolean sameHost(EID other) {
    return swigJNI.EID_sameHost__SWIG_1(swigCPtr, this, EID.getCPtr(other), other);
  }

  public String getString() {
    return swigJNI.EID_getString(swigCPtr, this);
  }

  public String getApplication() {
    return swigJNI.EID_getApplication(swigCPtr, this);
  }

  public String getHost() {
    return swigJNI.EID_getHost(swigCPtr, this);
  }

  public String getScheme() {
    return swigJNI.EID_getScheme(swigCPtr, this);
  }

  public String getSSP() {
    return swigJNI.EID_getSSP(swigCPtr, this);
  }

  public String getDelimiter() {
    return swigJNI.EID_getDelimiter(swigCPtr, this);
  }

  public EID getNode() {
    return new EID(swigJNI.EID_getNode(swigCPtr, this), true);
  }

  public boolean hasApplication() {
    return swigJNI.EID_hasApplication(swigCPtr, this);
  }

  public boolean isCompressable() {
    return swigJNI.EID_isCompressable(swigCPtr, this);
  }

  public boolean isNone() {
    return swigJNI.EID_isNone(swigCPtr, this);
  }

  public SWIGTYPE_p_std__pairT_size_t_size_t_t getCompressed() {
    return new SWIGTYPE_p_std__pairT_size_t_size_t_t(swigJNI.EID_getCompressed(swigCPtr, this), true);
  }

}
