/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.tubs.ibr.dtn.swig;

public class NativeSession {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected NativeSession(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NativeSession obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigJNI.delete_NativeSession(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public NativeSession(NativeSessionCallback cb) {
    this(swigJNI.new_NativeSession(NativeSessionCallback.getCPtr(cb), cb), true);
  }

  public EID getNodeEID() {
    return new EID(swigJNI.NativeSession_getNodeEID(swigCPtr, this), false);
  }

  public void setEndpoint(String suffix) {
    swigJNI.NativeSession_setEndpoint(swigCPtr, this, suffix);
  }

  public void resetEndpoint() {
    swigJNI.NativeSession_resetEndpoint(swigCPtr, this);
  }

  public void addEndpoint(String suffix) {
    swigJNI.NativeSession_addEndpoint(swigCPtr, this, suffix);
  }

  public void removeEndpoint(String suffix) {
    swigJNI.NativeSession_removeEndpoint(swigCPtr, this, suffix);
  }

  public void addRegistration(EID eid) {
    swigJNI.NativeSession_addRegistration(swigCPtr, this, EID.getCPtr(eid), eid);
  }

  public void removeRegistration(EID eid) {
    swigJNI.NativeSession_removeRegistration(swigCPtr, this, EID.getCPtr(eid), eid);
  }

  public void next(NativeSession.RegisterIndex ri) {
    swigJNI.NativeSession_next(swigCPtr, this, ri.swigValue());
  }

  public void load(NativeSession.RegisterIndex ri, BundleID id) {
    swigJNI.NativeSession_load(swigCPtr, this, ri.swigValue(), BundleID.getCPtr(id), id);
  }

  public SWIGTYPE_p_dtn__data__Bundle get(NativeSession.RegisterIndex ri) {
    return new SWIGTYPE_p_dtn__data__Bundle(swigJNI.NativeSession_get(swigCPtr, this, ri.swigValue()), false);
  }

  public void free(NativeSession.RegisterIndex ri) {
    swigJNI.NativeSession_free(swigCPtr, this, ri.swigValue());
  }

  public void clear(NativeSession.RegisterIndex ri) {
    swigJNI.NativeSession_clear(swigCPtr, this, ri.swigValue());
  }

  public void delivered(BundleID id) {
    swigJNI.NativeSession_delivered(swigCPtr, this, BundleID.getCPtr(id), id);
  }

  public void send(NativeSession.RegisterIndex ri) {
    swigJNI.NativeSession_send(swigCPtr, this, ri.swigValue());
  }

  public void put(NativeSession.RegisterIndex ri, SWIGTYPE_p_dtn__data__Bundle b) {
    swigJNI.NativeSession_put__SWIG_0(swigCPtr, this, ri.swigValue(), SWIGTYPE_p_dtn__data__Bundle.getCPtr(b));
  }

  public void put(NativeSession.RegisterIndex ri, PrimaryBlock b) {
    swigJNI.NativeSession_put__SWIG_1(swigCPtr, this, ri.swigValue(), PrimaryBlock.getCPtr(b), b);
  }

  public void write(NativeSession.RegisterIndex ri, byte[] buf, long offset) {
    swigJNI.NativeSession_write__SWIG_0(swigCPtr, this, ri.swigValue(), buf, offset);
  }

  public void write(NativeSession.RegisterIndex ri, byte[] buf) {
    swigJNI.NativeSession_write__SWIG_1(swigCPtr, this, ri.swigValue(), buf);
  }

  public void read(NativeSession.RegisterIndex ri, byte[] buf, int[] len, long offset) {
    swigJNI.NativeSession_read__SWIG_0(swigCPtr, this, ri.swigValue(), buf, len, offset);
  }

  public void read(NativeSession.RegisterIndex ri, byte[] buf, int[] len) {
    swigJNI.NativeSession_read__SWIG_1(swigCPtr, this, ri.swigValue(), buf, len);
  }

  public final static class RegisterIndex {
    public final static NativeSession.RegisterIndex REG1 = new NativeSession.RegisterIndex("REG1", swigJNI.NativeSession_REG1_get());
    public final static NativeSession.RegisterIndex REG2 = new NativeSession.RegisterIndex("REG2", swigJNI.NativeSession_REG2_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static RegisterIndex swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + RegisterIndex.class + " with value " + swigValue);
    }

    private RegisterIndex(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private RegisterIndex(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private RegisterIndex(String swigName, RegisterIndex swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static RegisterIndex[] swigValues = { REG1, REG2 };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
