/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.tubs.ibr.dtn.swig;

public class NativeSessionCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected NativeSessionCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NativeSessionCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigJNI.delete_NativeSessionCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void notifyBundle(SWIGTYPE_p_dtn__data__BundleID id) {
    swigJNI.NativeSessionCallback_notifyBundle(swigCPtr, this, SWIGTYPE_p_dtn__data__BundleID.getCPtr(id));
  }

  public void notifyStatusReport(SWIGTYPE_p_dtn__data__StatusReportBlock report) {
    swigJNI.NativeSessionCallback_notifyStatusReport(swigCPtr, this, SWIGTYPE_p_dtn__data__StatusReportBlock.getCPtr(report));
  }

  public void notifyCustodySignal(SWIGTYPE_p_dtn__data__CustodySignalBlock custody) {
    swigJNI.NativeSessionCallback_notifyCustodySignal(swigCPtr, this, SWIGTYPE_p_dtn__data__CustodySignalBlock.getCPtr(custody));
  }

}
