/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.tubs.ibr.dtn.swig;

public class NativeSessionCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected NativeSessionCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NativeSessionCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigJNI.delete_NativeSessionCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    swigJNI.NativeSessionCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    swigJNI.NativeSessionCallback_change_ownership(this, swigCPtr, true);
  }

  public void notifyBundle(BundleID id) {
    swigJNI.NativeSessionCallback_notifyBundle(swigCPtr, this, BundleID.getCPtr(id), id);
  }

  public void notifyStatusReport(SWIGTYPE_p_dtn__data__StatusReportBlock report) {
    swigJNI.NativeSessionCallback_notifyStatusReport(swigCPtr, this, SWIGTYPE_p_dtn__data__StatusReportBlock.getCPtr(report));
  }

  public void notifyCustodySignal(CustodySignalBlock custody) {
    swigJNI.NativeSessionCallback_notifyCustodySignal(swigCPtr, this, CustodySignalBlock.getCPtr(custody), custody);
  }

  public NativeSessionCallback() {
    this(swigJNI.new_NativeSessionCallback(), true);
    swigJNI.NativeSessionCallback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
