/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.tubs.ibr.dtn.swig;

public class PrimaryBlock {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PrimaryBlock(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PrimaryBlock obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigJNI.delete_PrimaryBlock(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PrimaryBlock() {
    this(swigJNI.new_PrimaryBlock(), true);
  }

  public boolean isExpired() {
    return swigJNI.PrimaryBlock_isExpired(swigCPtr, this);
  }

  public String toString() {
    return swigJNI.PrimaryBlock_toString(swigCPtr, this);
  }

  public void set(PrimaryBlock.FLAGS flag, boolean value) {
    swigJNI.PrimaryBlock_set(swigCPtr, this, flag.swigValue(), value);
  }

  public boolean get(PrimaryBlock.FLAGS flag) {
    return swigJNI.PrimaryBlock_get(swigCPtr, this, flag.swigValue());
  }

  public PrimaryBlock.PRIORITY getPriority() {
    return PrimaryBlock.PRIORITY.swigToEnum(swigJNI.PrimaryBlock_getPriority(swigCPtr, this));
  }

  public void setPriority(PrimaryBlock.PRIORITY p) {
    swigJNI.PrimaryBlock_setPriority(swigCPtr, this, p.swigValue());
  }

  public void relabel() {
    swigJNI.PrimaryBlock_relabel(swigCPtr, this);
  }

  public void set_procflags(long value) {
    swigJNI.PrimaryBlock__procflags_set(swigCPtr, this, value);
  }

  public long get_procflags() {
    return swigJNI.PrimaryBlock__procflags_get(swigCPtr, this);
  }

  public void set_timestamp(long value) {
    swigJNI.PrimaryBlock__timestamp_set(swigCPtr, this, value);
  }

  public long get_timestamp() {
    return swigJNI.PrimaryBlock__timestamp_get(swigCPtr, this);
  }

  public void set_sequencenumber(long value) {
    swigJNI.PrimaryBlock__sequencenumber_set(swigCPtr, this, value);
  }

  public long get_sequencenumber() {
    return swigJNI.PrimaryBlock__sequencenumber_get(swigCPtr, this);
  }

  public void set_lifetime(long value) {
    swigJNI.PrimaryBlock__lifetime_set(swigCPtr, this, value);
  }

  public long get_lifetime() {
    return swigJNI.PrimaryBlock__lifetime_get(swigCPtr, this);
  }

  public void set_fragmentoffset(long value) {
    swigJNI.PrimaryBlock__fragmentoffset_set(swigCPtr, this, value);
  }

  public long get_fragmentoffset() {
    return swigJNI.PrimaryBlock__fragmentoffset_get(swigCPtr, this);
  }

  public void set_appdatalength(long value) {
    swigJNI.PrimaryBlock__appdatalength_set(swigCPtr, this, value);
  }

  public long get_appdatalength() {
    return swigJNI.PrimaryBlock__appdatalength_get(swigCPtr, this);
  }

  public void set_source(EID value) {
    swigJNI.PrimaryBlock__source_set(swigCPtr, this, EID.getCPtr(value), value);
  }

  public EID get_source() {
    long cPtr = swigJNI.PrimaryBlock__source_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EID(cPtr, false);
  }

  public void set_destination(EID value) {
    swigJNI.PrimaryBlock__destination_set(swigCPtr, this, EID.getCPtr(value), value);
  }

  public EID get_destination() {
    long cPtr = swigJNI.PrimaryBlock__destination_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EID(cPtr, false);
  }

  public void set_reportto(EID value) {
    swigJNI.PrimaryBlock__reportto_set(swigCPtr, this, EID.getCPtr(value), value);
  }

  public EID get_reportto() {
    long cPtr = swigJNI.PrimaryBlock__reportto_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EID(cPtr, false);
  }

  public void set_custodian(EID value) {
    swigJNI.PrimaryBlock__custodian_set(swigCPtr, this, EID.getCPtr(value), value);
  }

  public EID get_custodian() {
    long cPtr = swigJNI.PrimaryBlock__custodian_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EID(cPtr, false);
  }

  public final static class PRIORITY {
    public final static PrimaryBlock.PRIORITY PRIO_LOW = new PrimaryBlock.PRIORITY("PRIO_LOW", swigJNI.PrimaryBlock_PRIO_LOW_get());
    public final static PrimaryBlock.PRIORITY PRIO_MEDIUM = new PrimaryBlock.PRIORITY("PRIO_MEDIUM", swigJNI.PrimaryBlock_PRIO_MEDIUM_get());
    public final static PrimaryBlock.PRIORITY PRIO_HIGH = new PrimaryBlock.PRIORITY("PRIO_HIGH", swigJNI.PrimaryBlock_PRIO_HIGH_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static PRIORITY swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + PRIORITY.class + " with value " + swigValue);
    }

    private PRIORITY(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private PRIORITY(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private PRIORITY(String swigName, PRIORITY swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static PRIORITY[] swigValues = { PRIO_LOW, PRIO_MEDIUM, PRIO_HIGH };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class FLAGS {
    public final static PrimaryBlock.FLAGS FRAGMENT = new PrimaryBlock.FLAGS("FRAGMENT", swigJNI.PrimaryBlock_FRAGMENT_get());
    public final static PrimaryBlock.FLAGS APPDATA_IS_ADMRECORD = new PrimaryBlock.FLAGS("APPDATA_IS_ADMRECORD", swigJNI.PrimaryBlock_APPDATA_IS_ADMRECORD_get());
    public final static PrimaryBlock.FLAGS DONT_FRAGMENT = new PrimaryBlock.FLAGS("DONT_FRAGMENT", swigJNI.PrimaryBlock_DONT_FRAGMENT_get());
    public final static PrimaryBlock.FLAGS CUSTODY_REQUESTED = new PrimaryBlock.FLAGS("CUSTODY_REQUESTED", swigJNI.PrimaryBlock_CUSTODY_REQUESTED_get());
    public final static PrimaryBlock.FLAGS DESTINATION_IS_SINGLETON = new PrimaryBlock.FLAGS("DESTINATION_IS_SINGLETON", swigJNI.PrimaryBlock_DESTINATION_IS_SINGLETON_get());
    public final static PrimaryBlock.FLAGS ACKOFAPP_REQUESTED = new PrimaryBlock.FLAGS("ACKOFAPP_REQUESTED", swigJNI.PrimaryBlock_ACKOFAPP_REQUESTED_get());
    public final static PrimaryBlock.FLAGS RESERVED_6 = new PrimaryBlock.FLAGS("RESERVED_6", swigJNI.PrimaryBlock_RESERVED_6_get());
    public final static PrimaryBlock.FLAGS PRIORITY_BIT1 = new PrimaryBlock.FLAGS("PRIORITY_BIT1", swigJNI.PrimaryBlock_PRIORITY_BIT1_get());
    public final static PrimaryBlock.FLAGS PRIORITY_BIT2 = new PrimaryBlock.FLAGS("PRIORITY_BIT2", swigJNI.PrimaryBlock_PRIORITY_BIT2_get());
    public final static PrimaryBlock.FLAGS CLASSOFSERVICE_9 = new PrimaryBlock.FLAGS("CLASSOFSERVICE_9", swigJNI.PrimaryBlock_CLASSOFSERVICE_9_get());
    public final static PrimaryBlock.FLAGS CLASSOFSERVICE_10 = new PrimaryBlock.FLAGS("CLASSOFSERVICE_10", swigJNI.PrimaryBlock_CLASSOFSERVICE_10_get());
    public final static PrimaryBlock.FLAGS CLASSOFSERVICE_11 = new PrimaryBlock.FLAGS("CLASSOFSERVICE_11", swigJNI.PrimaryBlock_CLASSOFSERVICE_11_get());
    public final static PrimaryBlock.FLAGS CLASSOFSERVICE_12 = new PrimaryBlock.FLAGS("CLASSOFSERVICE_12", swigJNI.PrimaryBlock_CLASSOFSERVICE_12_get());
    public final static PrimaryBlock.FLAGS CLASSOFSERVICE_13 = new PrimaryBlock.FLAGS("CLASSOFSERVICE_13", swigJNI.PrimaryBlock_CLASSOFSERVICE_13_get());
    public final static PrimaryBlock.FLAGS REQUEST_REPORT_OF_BUNDLE_RECEPTION = new PrimaryBlock.FLAGS("REQUEST_REPORT_OF_BUNDLE_RECEPTION", swigJNI.PrimaryBlock_REQUEST_REPORT_OF_BUNDLE_RECEPTION_get());
    public final static PrimaryBlock.FLAGS REQUEST_REPORT_OF_CUSTODY_ACCEPTANCE = new PrimaryBlock.FLAGS("REQUEST_REPORT_OF_CUSTODY_ACCEPTANCE", swigJNI.PrimaryBlock_REQUEST_REPORT_OF_CUSTODY_ACCEPTANCE_get());
    public final static PrimaryBlock.FLAGS REQUEST_REPORT_OF_BUNDLE_FORWARDING = new PrimaryBlock.FLAGS("REQUEST_REPORT_OF_BUNDLE_FORWARDING", swigJNI.PrimaryBlock_REQUEST_REPORT_OF_BUNDLE_FORWARDING_get());
    public final static PrimaryBlock.FLAGS REQUEST_REPORT_OF_BUNDLE_DELIVERY = new PrimaryBlock.FLAGS("REQUEST_REPORT_OF_BUNDLE_DELIVERY", swigJNI.PrimaryBlock_REQUEST_REPORT_OF_BUNDLE_DELIVERY_get());
    public final static PrimaryBlock.FLAGS REQUEST_REPORT_OF_BUNDLE_DELETION = new PrimaryBlock.FLAGS("REQUEST_REPORT_OF_BUNDLE_DELETION", swigJNI.PrimaryBlock_REQUEST_REPORT_OF_BUNDLE_DELETION_get());
    public final static PrimaryBlock.FLAGS STATUS_REPORT_REQUEST_19 = new PrimaryBlock.FLAGS("STATUS_REPORT_REQUEST_19", swigJNI.PrimaryBlock_STATUS_REPORT_REQUEST_19_get());
    public final static PrimaryBlock.FLAGS STATUS_REPORT_REQUEST_20 = new PrimaryBlock.FLAGS("STATUS_REPORT_REQUEST_20", swigJNI.PrimaryBlock_STATUS_REPORT_REQUEST_20_get());
    public final static PrimaryBlock.FLAGS DTNSEC_REQUEST_SIGN = new PrimaryBlock.FLAGS("DTNSEC_REQUEST_SIGN", swigJNI.PrimaryBlock_DTNSEC_REQUEST_SIGN_get());
    public final static PrimaryBlock.FLAGS DTNSEC_REQUEST_ENCRYPT = new PrimaryBlock.FLAGS("DTNSEC_REQUEST_ENCRYPT", swigJNI.PrimaryBlock_DTNSEC_REQUEST_ENCRYPT_get());
    public final static PrimaryBlock.FLAGS DTNSEC_STATUS_VERIFIED = new PrimaryBlock.FLAGS("DTNSEC_STATUS_VERIFIED", swigJNI.PrimaryBlock_DTNSEC_STATUS_VERIFIED_get());
    public final static PrimaryBlock.FLAGS DTNSEC_STATUS_CONFIDENTIAL = new PrimaryBlock.FLAGS("DTNSEC_STATUS_CONFIDENTIAL", swigJNI.PrimaryBlock_DTNSEC_STATUS_CONFIDENTIAL_get());
    public final static PrimaryBlock.FLAGS DTNSEC_STATUS_AUTHENTICATED = new PrimaryBlock.FLAGS("DTNSEC_STATUS_AUTHENTICATED", swigJNI.PrimaryBlock_DTNSEC_STATUS_AUTHENTICATED_get());
    public final static PrimaryBlock.FLAGS IBRDTN_REQUEST_COMPRESSION = new PrimaryBlock.FLAGS("IBRDTN_REQUEST_COMPRESSION", swigJNI.PrimaryBlock_IBRDTN_REQUEST_COMPRESSION_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static FLAGS swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + FLAGS.class + " with value " + swigValue);
    }

    private FLAGS(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private FLAGS(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private FLAGS(String swigName, FLAGS swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static FLAGS[] swigValues = { FRAGMENT, APPDATA_IS_ADMRECORD, DONT_FRAGMENT, CUSTODY_REQUESTED, DESTINATION_IS_SINGLETON, ACKOFAPP_REQUESTED, RESERVED_6, PRIORITY_BIT1, PRIORITY_BIT2, CLASSOFSERVICE_9, CLASSOFSERVICE_10, CLASSOFSERVICE_11, CLASSOFSERVICE_12, CLASSOFSERVICE_13, REQUEST_REPORT_OF_BUNDLE_RECEPTION, REQUEST_REPORT_OF_CUSTODY_ACCEPTANCE, REQUEST_REPORT_OF_BUNDLE_FORWARDING, REQUEST_REPORT_OF_BUNDLE_DELIVERY, REQUEST_REPORT_OF_BUNDLE_DELETION, STATUS_REPORT_REQUEST_19, STATUS_REPORT_REQUEST_20, DTNSEC_REQUEST_SIGN, DTNSEC_REQUEST_ENCRYPT, DTNSEC_STATUS_VERIFIED, DTNSEC_STATUS_CONFIDENTIAL, DTNSEC_STATUS_AUTHENTICATED, IBRDTN_REQUEST_COMPRESSION };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
