/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.tubs.ibr.dtn.swig;

public class SDNV {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDNV(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDNV obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigJNI.delete_SDNV(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SDNV(SWIGTYPE_p_uint64_t value) {
    this(swigJNI.new_SDNV__SWIG_0(SWIGTYPE_p_uint64_t.getCPtr(value)), true);
  }

  public SDNV() {
    this(swigJNI.new_SDNV__SWIG_1(), true);
  }

  public long getLength() {
    return swigJNI.SDNV_getLength__SWIG_0(swigCPtr, this);
  }

  public static long getLength(SWIGTYPE_p_uint64_t value) {
    return swigJNI.SDNV_getLength__SWIG_1(SWIGTYPE_p_uint64_t.getCPtr(value));
  }

  public static long getLength(SWIGTYPE_p_unsigned_char data) {
    return swigJNI.SDNV_getLength__SWIG_2(SWIGTYPE_p_unsigned_char.getCPtr(data));
  }

  public SWIGTYPE_p_uint64_t getValue() {
    return new SWIGTYPE_p_uint64_t(swigJNI.SDNV_getValue(swigCPtr, this), true);
  }

  public long decode(String data, long len) {
    return swigJNI.SDNV_decode(swigCPtr, this, data, len);
  }

  public long encode(String data, long len) {
    return swigJNI.SDNV_encode(swigCPtr, this, data, len);
  }

  public final static long MAX_LENGTH = swigJNI.SDNV_MAX_LENGTH_get();
}
