/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.tubs.ibr.dtn.swig;

public class StatusReportBlock extends AdministrativeBlock {
  private long swigCPtr;

  protected StatusReportBlock(long cPtr, boolean cMemoryOwn) {
    super(swigJNI.StatusReportBlock_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StatusReportBlock obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigJNI.delete_StatusReportBlock(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public StatusReportBlock() {
    this(swigJNI.new_StatusReportBlock(), true);
  }

  public void read(SWIGTYPE_p_dtn__data__PayloadBlock p) {
    swigJNI.StatusReportBlock_read(swigCPtr, this, SWIGTYPE_p_dtn__data__PayloadBlock.getCPtr(p));
  }

  public void write(SWIGTYPE_p_dtn__data__PayloadBlock p) {
    swigJNI.StatusReportBlock_write(swigCPtr, this, SWIGTYPE_p_dtn__data__PayloadBlock.getCPtr(p));
  }

  public void set_status(char value) {
    swigJNI.StatusReportBlock__status_set(swigCPtr, this, value);
  }

  public char get_status() {
    return swigJNI.StatusReportBlock__status_get(swigCPtr, this);
  }

  public void set_reasoncode(char value) {
    swigJNI.StatusReportBlock__reasoncode_set(swigCPtr, this, value);
  }

  public char get_reasoncode() {
    return swigJNI.StatusReportBlock__reasoncode_get(swigCPtr, this);
  }

  public void set_fragment_offset(SDNV value) {
    swigJNI.StatusReportBlock__fragment_offset_set(swigCPtr, this, SDNV.getCPtr(value), value);
  }

  public SDNV get_fragment_offset() {
    long cPtr = swigJNI.StatusReportBlock__fragment_offset_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDNV(cPtr, false);
  }

  public void set_fragment_length(SDNV value) {
    swigJNI.StatusReportBlock__fragment_length_set(swigCPtr, this, SDNV.getCPtr(value), value);
  }

  public SDNV get_fragment_length() {
    long cPtr = swigJNI.StatusReportBlock__fragment_length_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDNV(cPtr, false);
  }

  public void set_timeof_receipt(DTNTime value) {
    swigJNI.StatusReportBlock__timeof_receipt_set(swigCPtr, this, DTNTime.getCPtr(value), value);
  }

  public DTNTime get_timeof_receipt() {
    long cPtr = swigJNI.StatusReportBlock__timeof_receipt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DTNTime(cPtr, false);
  }

  public void set_timeof_custodyaccept(DTNTime value) {
    swigJNI.StatusReportBlock__timeof_custodyaccept_set(swigCPtr, this, DTNTime.getCPtr(value), value);
  }

  public DTNTime get_timeof_custodyaccept() {
    long cPtr = swigJNI.StatusReportBlock__timeof_custodyaccept_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DTNTime(cPtr, false);
  }

  public void set_timeof_forwarding(DTNTime value) {
    swigJNI.StatusReportBlock__timeof_forwarding_set(swigCPtr, this, DTNTime.getCPtr(value), value);
  }

  public DTNTime get_timeof_forwarding() {
    long cPtr = swigJNI.StatusReportBlock__timeof_forwarding_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DTNTime(cPtr, false);
  }

  public void set_timeof_delivery(DTNTime value) {
    swigJNI.StatusReportBlock__timeof_delivery_set(swigCPtr, this, DTNTime.getCPtr(value), value);
  }

  public DTNTime get_timeof_delivery() {
    long cPtr = swigJNI.StatusReportBlock__timeof_delivery_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DTNTime(cPtr, false);
  }

  public void set_timeof_deletion(DTNTime value) {
    swigJNI.StatusReportBlock__timeof_deletion_set(swigCPtr, this, DTNTime.getCPtr(value), value);
  }

  public DTNTime get_timeof_deletion() {
    long cPtr = swigJNI.StatusReportBlock__timeof_deletion_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DTNTime(cPtr, false);
  }

  public void set_bundle_timestamp(SDNV value) {
    swigJNI.StatusReportBlock__bundle_timestamp_set(swigCPtr, this, SDNV.getCPtr(value), value);
  }

  public SDNV get_bundle_timestamp() {
    long cPtr = swigJNI.StatusReportBlock__bundle_timestamp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDNV(cPtr, false);
  }

  public void set_bundle_sequence(SDNV value) {
    swigJNI.StatusReportBlock__bundle_sequence_set(swigCPtr, this, SDNV.getCPtr(value), value);
  }

  public SDNV get_bundle_sequence() {
    long cPtr = swigJNI.StatusReportBlock__bundle_sequence_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SDNV(cPtr, false);
  }

  public void set_source(EID value) {
    swigJNI.StatusReportBlock__source_set(swigCPtr, this, EID.getCPtr(value), value);
  }

  public EID get_source() {
    long cPtr = swigJNI.StatusReportBlock__source_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EID(cPtr, false);
  }

  public final static class TYPE {
    public final static StatusReportBlock.TYPE RECEIPT_OF_BUNDLE = new StatusReportBlock.TYPE("RECEIPT_OF_BUNDLE", swigJNI.StatusReportBlock_RECEIPT_OF_BUNDLE_get());
    public final static StatusReportBlock.TYPE CUSTODY_ACCEPTANCE_OF_BUNDLE = new StatusReportBlock.TYPE("CUSTODY_ACCEPTANCE_OF_BUNDLE", swigJNI.StatusReportBlock_CUSTODY_ACCEPTANCE_OF_BUNDLE_get());
    public final static StatusReportBlock.TYPE FORWARDING_OF_BUNDLE = new StatusReportBlock.TYPE("FORWARDING_OF_BUNDLE", swigJNI.StatusReportBlock_FORWARDING_OF_BUNDLE_get());
    public final static StatusReportBlock.TYPE DELIVERY_OF_BUNDLE = new StatusReportBlock.TYPE("DELIVERY_OF_BUNDLE", swigJNI.StatusReportBlock_DELIVERY_OF_BUNDLE_get());
    public final static StatusReportBlock.TYPE DELETION_OF_BUNDLE = new StatusReportBlock.TYPE("DELETION_OF_BUNDLE", swigJNI.StatusReportBlock_DELETION_OF_BUNDLE_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static TYPE swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + TYPE.class + " with value " + swigValue);
    }

    private TYPE(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private TYPE(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private TYPE(String swigName, TYPE swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static TYPE[] swigValues = { RECEIPT_OF_BUNDLE, CUSTODY_ACCEPTANCE_OF_BUNDLE, FORWARDING_OF_BUNDLE, DELIVERY_OF_BUNDLE, DELETION_OF_BUNDLE };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

  public final static class REASON_CODE {
    public final static StatusReportBlock.REASON_CODE NO_ADDITIONAL_INFORMATION = new StatusReportBlock.REASON_CODE("NO_ADDITIONAL_INFORMATION", swigJNI.StatusReportBlock_NO_ADDITIONAL_INFORMATION_get());
    public final static StatusReportBlock.REASON_CODE LIFETIME_EXPIRED = new StatusReportBlock.REASON_CODE("LIFETIME_EXPIRED", swigJNI.StatusReportBlock_LIFETIME_EXPIRED_get());
    public final static StatusReportBlock.REASON_CODE FORWARDED_OVER_UNIDIRECTIONAL_LINK = new StatusReportBlock.REASON_CODE("FORWARDED_OVER_UNIDIRECTIONAL_LINK", swigJNI.StatusReportBlock_FORWARDED_OVER_UNIDIRECTIONAL_LINK_get());
    public final static StatusReportBlock.REASON_CODE TRANSMISSION_CANCELED = new StatusReportBlock.REASON_CODE("TRANSMISSION_CANCELED", swigJNI.StatusReportBlock_TRANSMISSION_CANCELED_get());
    public final static StatusReportBlock.REASON_CODE DEPLETED_STORAGE = new StatusReportBlock.REASON_CODE("DEPLETED_STORAGE", swigJNI.StatusReportBlock_DEPLETED_STORAGE_get());
    public final static StatusReportBlock.REASON_CODE DESTINATION_ENDPOINT_ID_UNINTELLIGIBLE = new StatusReportBlock.REASON_CODE("DESTINATION_ENDPOINT_ID_UNINTELLIGIBLE", swigJNI.StatusReportBlock_DESTINATION_ENDPOINT_ID_UNINTELLIGIBLE_get());
    public final static StatusReportBlock.REASON_CODE NO_KNOWN_ROUTE_TO_DESTINATION_FROM_HERE = new StatusReportBlock.REASON_CODE("NO_KNOWN_ROUTE_TO_DESTINATION_FROM_HERE", swigJNI.StatusReportBlock_NO_KNOWN_ROUTE_TO_DESTINATION_FROM_HERE_get());
    public final static StatusReportBlock.REASON_CODE NO_TIMELY_CONTACT_WITH_NEXT_NODE_ON_ROUTE = new StatusReportBlock.REASON_CODE("NO_TIMELY_CONTACT_WITH_NEXT_NODE_ON_ROUTE", swigJNI.StatusReportBlock_NO_TIMELY_CONTACT_WITH_NEXT_NODE_ON_ROUTE_get());
    public final static StatusReportBlock.REASON_CODE BLOCK_UNINTELLIGIBLE = new StatusReportBlock.REASON_CODE("BLOCK_UNINTELLIGIBLE", swigJNI.StatusReportBlock_BLOCK_UNINTELLIGIBLE_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static REASON_CODE swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + REASON_CODE.class + " with value " + swigValue);
    }

    private REASON_CODE(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private REASON_CODE(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private REASON_CODE(String swigName, REASON_CODE swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static REASON_CODE[] swigValues = { NO_ADDITIONAL_INFORMATION, LIFETIME_EXPIRED, FORWARDED_OVER_UNIDIRECTIONAL_LINK, TRANSMISSION_CANCELED, DEPLETED_STORAGE, DESTINATION_ENDPOINT_ID_UNINTELLIGIBLE, NO_KNOWN_ROUTE_TO_DESTINATION_FROM_HERE, NO_TIMELY_CONTACT_WITH_NEXT_NODE_ON_ROUTE, BLOCK_UNINTELLIGIBLE };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
