/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.tubs.ibr.dtn.swig;

public class SWIGTYPE_p_SDNV {
  private long swigCPtr;

  protected SWIGTYPE_p_SDNV(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_SDNV() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_SDNV obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

