/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.tubs.ibr.dtn.swig;

public class swigJNI {
  public final static native long new_NativeSessionException__SWIG_0(long jarg1);
  public final static native long new_NativeSessionException__SWIG_1();
  public final static native void delete_NativeSessionException(long jarg1);
  public final static native long new_BundleNotFoundException__SWIG_0(long jarg1);
  public final static native long new_BundleNotFoundException__SWIG_1();
  public final static native void delete_BundleNotFoundException(long jarg1);
  public final static native void delete_NativeSessionCallback(long jarg1);
  public final static native void NativeSessionCallback_notifyBundle(long jarg1, NativeSessionCallback jarg1_, long jarg2);
  public final static native void NativeSessionCallback_notifyStatusReport(long jarg1, NativeSessionCallback jarg1_, long jarg2);
  public final static native void NativeSessionCallback_notifyCustodySignal(long jarg1, NativeSessionCallback jarg1_, long jarg2);
  public final static native int NativeSession_REG1_get();
  public final static native int NativeSession_REG2_get();
  public final static native long new_NativeSession(long jarg1, NativeSessionCallback jarg1_);
  public final static native void delete_NativeSession(long jarg1);
  public final static native long NativeSession_getNodeEID(long jarg1, NativeSession jarg1_);
  public final static native void NativeSession_setEndpoint(long jarg1, NativeSession jarg1_, long jarg2);
  public final static native void NativeSession_resetEndpoint(long jarg1, NativeSession jarg1_);
  public final static native void NativeSession_addEndpoint(long jarg1, NativeSession jarg1_, long jarg2);
  public final static native void NativeSession_removeEndpoint(long jarg1, NativeSession jarg1_, long jarg2);
  public final static native void NativeSession_addRegistration(long jarg1, NativeSession jarg1_, long jarg2);
  public final static native void NativeSession_removeRegistration(long jarg1, NativeSession jarg1_, long jarg2);
  public final static native void NativeSession_next(long jarg1, NativeSession jarg1_, int jarg2);
  public final static native void NativeSession_load(long jarg1, NativeSession jarg1_, int jarg2, long jarg3);
  public final static native long NativeSession_get(long jarg1, NativeSession jarg1_, int jarg2);
  public final static native void NativeSession_free(long jarg1, NativeSession jarg1_, int jarg2);
  public final static native void NativeSession_clear(long jarg1, NativeSession jarg1_, int jarg2);
  public final static native void NativeSession_delivered(long jarg1, NativeSession jarg1_, long jarg2);
  public final static native void NativeSession_send(long jarg1, NativeSession jarg1_, int jarg2);
  public final static native void NativeSession_put(long jarg1, NativeSession jarg1_, int jarg2, long jarg3);
  public final static native void NativeSession_write__SWIG_0(long jarg1, NativeSession jarg1_, int jarg2, String jarg3, long jarg4, long jarg5);
  public final static native void NativeSession_write__SWIG_1(long jarg1, NativeSession jarg1_, int jarg2, String jarg3, long jarg4);
  public final static native void NativeSession_read__SWIG_0(long jarg1, NativeSession jarg1_, int jarg2, String jarg3, long jarg4, long jarg5);
  public final static native void NativeSession_read__SWIG_1(long jarg1, NativeSession jarg1_, int jarg2, String jarg3, long jarg4);
}
