/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_tubs_ibr_dtn_service_NativeLibraryWrapper */

#ifndef _Included_de_tubs_ibr_dtn_service_NativeLibraryWrapper
#define _Included_de_tubs_ibr_dtn_service_NativeLibraryWrapper
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     de_tubs_ibr_dtn_service_NativeLibraryWrapper
 * Method:    daemonInitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tubs_ibr_dtn_service_NativeLibraryWrapper_daemonInitialize
  (JNIEnv *, jclass);

/*
 * Class:     de_tubs_ibr_dtn_service_NativeLibraryWrapper
 * Method:    daemonMainLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tubs_ibr_dtn_service_NativeLibraryWrapper_daemonMainLoop
  (JNIEnv *, jclass);

/*
 * Class:     de_tubs_ibr_dtn_service_NativeLibraryWrapper
 * Method:    daemonShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tubs_ibr_dtn_service_NativeLibraryWrapper_daemonShutdown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
