/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "../dtnd/src/api/NativeSession.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_new_1NativeSessionException_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  string arg1 ;
  string *argp1 ;
  dtn::api::NativeSessionException *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(string **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null string");
    return 0;
  }
  arg1 = *argp1; 
  result = (dtn::api::NativeSessionException *)new dtn::api::NativeSessionException(arg1);
  *(dtn::api::NativeSessionException **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_new_1NativeSessionException_1_1SWIG_11(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  dtn::api::NativeSessionException *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (dtn::api::NativeSessionException *)new dtn::api::NativeSessionException();
  *(dtn::api::NativeSessionException **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_delete_1NativeSessionException(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  dtn::api::NativeSessionException *arg1 = (dtn::api::NativeSessionException *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(dtn::api::NativeSessionException **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_new_1BundleNotFoundException_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  string arg1 ;
  string *argp1 ;
  dtn::api::BundleNotFoundException *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(string **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null string");
    return 0;
  }
  arg1 = *argp1; 
  result = (dtn::api::BundleNotFoundException *)new dtn::api::BundleNotFoundException(arg1);
  *(dtn::api::BundleNotFoundException **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_new_1BundleNotFoundException_1_1SWIG_11(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  dtn::api::BundleNotFoundException *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (dtn::api::BundleNotFoundException *)new dtn::api::BundleNotFoundException();
  *(dtn::api::BundleNotFoundException **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_delete_1BundleNotFoundException(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  dtn::api::BundleNotFoundException *arg1 = (dtn::api::BundleNotFoundException *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(dtn::api::BundleNotFoundException **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_delete_1NativeSessionCallback(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  dtn::api::NativeSessionCallback *arg1 = (dtn::api::NativeSessionCallback *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(dtn::api::NativeSessionCallback **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_NativeSessionCallback_1notifyBundle(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  dtn::api::NativeSessionCallback *arg1 = (dtn::api::NativeSessionCallback *) 0 ;
  dtn::data::BundleID *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dtn::api::NativeSessionCallback **)&jarg1; 
  arg2 = *(dtn::data::BundleID **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "dtn::data::BundleID const & reference is null");
    return ;
  } 
  (arg1)->notifyBundle((dtn::data::BundleID const &)*arg2);
}


SWIGEXPORT void JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_NativeSessionCallback_1notifyStatusReport(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  dtn::api::NativeSessionCallback *arg1 = (dtn::api::NativeSessionCallback *) 0 ;
  dtn::data::StatusReportBlock *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dtn::api::NativeSessionCallback **)&jarg1; 
  arg2 = *(dtn::data::StatusReportBlock **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "dtn::data::StatusReportBlock const & reference is null");
    return ;
  } 
  (arg1)->notifyStatusReport((dtn::data::StatusReportBlock const &)*arg2);
}


SWIGEXPORT void JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_NativeSessionCallback_1notifyCustodySignal(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  dtn::api::NativeSessionCallback *arg1 = (dtn::api::NativeSessionCallback *) 0 ;
  dtn::data::CustodySignalBlock *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dtn::api::NativeSessionCallback **)&jarg1; 
  arg2 = *(dtn::data::CustodySignalBlock **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "dtn::data::CustodySignalBlock const & reference is null");
    return ;
  } 
  (arg1)->notifyCustodySignal((dtn::data::CustodySignalBlock const &)*arg2);
}


SWIGEXPORT jint JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_NativeSession_1REG1_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  dtn::api::NativeSession::RegisterIndex result;
  
  (void)jenv;
  (void)jcls;
  result = (dtn::api::NativeSession::RegisterIndex)dtn::api::NativeSession::REG1;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_NativeSession_1REG2_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  dtn::api::NativeSession::RegisterIndex result;
  
  (void)jenv;
  (void)jcls;
  result = (dtn::api::NativeSession::RegisterIndex)dtn::api::NativeSession::REG2;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_new_1NativeSession(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  dtn::api::NativeSessionCallback *arg1 = (dtn::api::NativeSessionCallback *) 0 ;
  dtn::api::NativeSession *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dtn::api::NativeSessionCallback **)&jarg1; 
  result = (dtn::api::NativeSession *)new dtn::api::NativeSession(arg1);
  *(dtn::api::NativeSession **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_delete_1NativeSession(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  dtn::api::NativeSession *arg1 = (dtn::api::NativeSession *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(dtn::api::NativeSession **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_NativeSession_1getNodeEID(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  dtn::api::NativeSession *arg1 = (dtn::api::NativeSession *) 0 ;
  dtn::data::EID *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dtn::api::NativeSession **)&jarg1; 
  result = (dtn::data::EID *) &((dtn::api::NativeSession const *)arg1)->getNodeEID();
  *(dtn::data::EID **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_NativeSession_1setEndpoint(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  dtn::api::NativeSession *arg1 = (dtn::api::NativeSession *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dtn::api::NativeSession **)&jarg1; 
  arg2 = *(std::string **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::string const & reference is null");
    return ;
  } 
  try {
    (arg1)->setEndpoint((std::string const &)*arg2);
  }
  catch(dtn::api::NativeSessionException &_e) {
    (void)_e;
    SWIG_JavaThrowException(jenv, SWIG_JavaRuntimeException, "C++ dtn::api::NativeSessionException exception thrown");
    return ; 
  }
  
}


SWIGEXPORT void JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_NativeSession_1resetEndpoint(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  dtn::api::NativeSession *arg1 = (dtn::api::NativeSession *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dtn::api::NativeSession **)&jarg1; 
  (arg1)->resetEndpoint();
}


SWIGEXPORT void JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_NativeSession_1addEndpoint(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  dtn::api::NativeSession *arg1 = (dtn::api::NativeSession *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dtn::api::NativeSession **)&jarg1; 
  arg2 = *(std::string **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::string const & reference is null");
    return ;
  } 
  try {
    (arg1)->addEndpoint((std::string const &)*arg2);
  }
  catch(dtn::api::NativeSessionException &_e) {
    (void)_e;
    SWIG_JavaThrowException(jenv, SWIG_JavaRuntimeException, "C++ dtn::api::NativeSessionException exception thrown");
    return ; 
  }
  
}


SWIGEXPORT void JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_NativeSession_1removeEndpoint(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  dtn::api::NativeSession *arg1 = (dtn::api::NativeSession *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dtn::api::NativeSession **)&jarg1; 
  arg2 = *(std::string **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::string const & reference is null");
    return ;
  } 
  try {
    (arg1)->removeEndpoint((std::string const &)*arg2);
  }
  catch(dtn::api::NativeSessionException &_e) {
    (void)_e;
    SWIG_JavaThrowException(jenv, SWIG_JavaRuntimeException, "C++ dtn::api::NativeSessionException exception thrown");
    return ; 
  }
  
}


SWIGEXPORT void JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_NativeSession_1addRegistration(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  dtn::api::NativeSession *arg1 = (dtn::api::NativeSession *) 0 ;
  dtn::data::EID *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dtn::api::NativeSession **)&jarg1; 
  arg2 = *(dtn::data::EID **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "dtn::data::EID const & reference is null");
    return ;
  } 
  try {
    (arg1)->addRegistration((dtn::data::EID const &)*arg2);
  }
  catch(dtn::api::NativeSessionException &_e) {
    (void)_e;
    SWIG_JavaThrowException(jenv, SWIG_JavaRuntimeException, "C++ dtn::api::NativeSessionException exception thrown");
    return ; 
  }
  
}


SWIGEXPORT void JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_NativeSession_1removeRegistration(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  dtn::api::NativeSession *arg1 = (dtn::api::NativeSession *) 0 ;
  dtn::data::EID *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dtn::api::NativeSession **)&jarg1; 
  arg2 = *(dtn::data::EID **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "dtn::data::EID const & reference is null");
    return ;
  } 
  try {
    (arg1)->removeRegistration((dtn::data::EID const &)*arg2);
  }
  catch(dtn::api::NativeSessionException &_e) {
    (void)_e;
    SWIG_JavaThrowException(jenv, SWIG_JavaRuntimeException, "C++ dtn::api::NativeSessionException exception thrown");
    return ; 
  }
  
}


SWIGEXPORT void JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_NativeSession_1next(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  dtn::api::NativeSession *arg1 = (dtn::api::NativeSession *) 0 ;
  dtn::api::NativeSession::RegisterIndex arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dtn::api::NativeSession **)&jarg1; 
  arg2 = (dtn::api::NativeSession::RegisterIndex)jarg2; 
  try {
    (arg1)->next(arg2);
  }
  catch(dtn::api::NativeSessionException &_e) {
    (void)_e;
    SWIG_JavaThrowException(jenv, SWIG_JavaRuntimeException, "C++ dtn::api::NativeSessionException exception thrown");
    return ; 
  }
  
}


SWIGEXPORT void JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_NativeSession_1load(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3) {
  dtn::api::NativeSession *arg1 = (dtn::api::NativeSession *) 0 ;
  dtn::api::NativeSession::RegisterIndex arg2 ;
  dtn::data::BundleID *arg3 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dtn::api::NativeSession **)&jarg1; 
  arg2 = (dtn::api::NativeSession::RegisterIndex)jarg2; 
  arg3 = *(dtn::data::BundleID **)&jarg3;
  if (!arg3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "dtn::data::BundleID const & reference is null");
    return ;
  } 
  try {
    (arg1)->load(arg2,(dtn::data::BundleID const &)*arg3);
  }
  catch(dtn::api::NativeSessionException &_e) {
    (void)_e;
    SWIG_JavaThrowException(jenv, SWIG_JavaRuntimeException, "C++ dtn::api::NativeSessionException exception thrown");
    return ; 
  }
  
}


SWIGEXPORT jlong JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_NativeSession_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  dtn::api::NativeSession *arg1 = (dtn::api::NativeSession *) 0 ;
  dtn::api::NativeSession::RegisterIndex arg2 ;
  dtn::data::Bundle *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dtn::api::NativeSession **)&jarg1; 
  arg2 = (dtn::api::NativeSession::RegisterIndex)jarg2; 
  result = (dtn::data::Bundle *) &((dtn::api::NativeSession const *)arg1)->get(arg2);
  *(dtn::data::Bundle **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_NativeSession_1free(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  dtn::api::NativeSession *arg1 = (dtn::api::NativeSession *) 0 ;
  dtn::api::NativeSession::RegisterIndex arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dtn::api::NativeSession **)&jarg1; 
  arg2 = (dtn::api::NativeSession::RegisterIndex)jarg2; 
  try {
    (arg1)->free(arg2);
  }
  catch(dtn::api::BundleNotFoundException &_e) {
    (void)_e;
    SWIG_JavaThrowException(jenv, SWIG_JavaRuntimeException, "C++ dtn::api::BundleNotFoundException exception thrown");
    return ; 
  }
  
}


SWIGEXPORT void JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_NativeSession_1clear(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  dtn::api::NativeSession *arg1 = (dtn::api::NativeSession *) 0 ;
  dtn::api::NativeSession::RegisterIndex arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dtn::api::NativeSession **)&jarg1; 
  arg2 = (dtn::api::NativeSession::RegisterIndex)jarg2; 
  (arg1)->clear(arg2);
}


SWIGEXPORT void JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_NativeSession_1delivered(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  dtn::api::NativeSession *arg1 = (dtn::api::NativeSession *) 0 ;
  dtn::data::BundleID *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dtn::api::NativeSession **)&jarg1; 
  arg2 = *(dtn::data::BundleID **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "dtn::data::BundleID const & reference is null");
    return ;
  } 
  try {
    (arg1)->delivered((dtn::data::BundleID const &)*arg2);
  }
  catch(dtn::api::BundleNotFoundException &_e) {
    (void)_e;
    SWIG_JavaThrowException(jenv, SWIG_JavaRuntimeException, "C++ dtn::api::BundleNotFoundException exception thrown");
    return ; 
  }
  
}


SWIGEXPORT void JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_NativeSession_1send(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  dtn::api::NativeSession *arg1 = (dtn::api::NativeSession *) 0 ;
  dtn::api::NativeSession::RegisterIndex arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dtn::api::NativeSession **)&jarg1; 
  arg2 = (dtn::api::NativeSession::RegisterIndex)jarg2; 
  (arg1)->send(arg2);
}


SWIGEXPORT void JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_NativeSession_1put(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3) {
  dtn::api::NativeSession *arg1 = (dtn::api::NativeSession *) 0 ;
  dtn::api::NativeSession::RegisterIndex arg2 ;
  dtn::data::Bundle *arg3 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dtn::api::NativeSession **)&jarg1; 
  arg2 = (dtn::api::NativeSession::RegisterIndex)jarg2; 
  arg3 = *(dtn::data::Bundle **)&jarg3;
  if (!arg3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "dtn::data::Bundle const & reference is null");
    return ;
  } 
  (arg1)->put(arg2,(dtn::data::Bundle const &)*arg3);
}


SWIGEXPORT void JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_NativeSession_1write_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jstring jarg3, jlong jarg4, jlong jarg5) {
  dtn::api::NativeSession *arg1 = (dtn::api::NativeSession *) 0 ;
  dtn::api::NativeSession::RegisterIndex arg2 ;
  char *arg3 = (char *) 0 ;
  size_t arg4 ;
  size_t arg5 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dtn::api::NativeSession **)&jarg1; 
  arg2 = (dtn::api::NativeSession::RegisterIndex)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)jenv->GetStringUTFChars(jarg3, 0);
    if (!arg3) return ;
  }
  arg4 = (size_t)jarg4; 
  arg5 = (size_t)jarg5; 
  (arg1)->write(arg2,(char const *)arg3,arg4,arg5);
  if (arg3) jenv->ReleaseStringUTFChars(jarg3, (const char *)arg3);
}


SWIGEXPORT void JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_NativeSession_1write_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jstring jarg3, jlong jarg4) {
  dtn::api::NativeSession *arg1 = (dtn::api::NativeSession *) 0 ;
  dtn::api::NativeSession::RegisterIndex arg2 ;
  char *arg3 = (char *) 0 ;
  size_t arg4 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dtn::api::NativeSession **)&jarg1; 
  arg2 = (dtn::api::NativeSession::RegisterIndex)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)jenv->GetStringUTFChars(jarg3, 0);
    if (!arg3) return ;
  }
  arg4 = (size_t)jarg4; 
  (arg1)->write(arg2,(char const *)arg3,arg4);
  if (arg3) jenv->ReleaseStringUTFChars(jarg3, (const char *)arg3);
}


SWIGEXPORT void JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_NativeSession_1read_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jstring jarg3, jlong jarg4, jlong jarg5) {
  dtn::api::NativeSession *arg1 = (dtn::api::NativeSession *) 0 ;
  dtn::api::NativeSession::RegisterIndex arg2 ;
  char *arg3 = (char *) 0 ;
  size_t *arg4 = 0 ;
  size_t arg5 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dtn::api::NativeSession **)&jarg1; 
  arg2 = (dtn::api::NativeSession::RegisterIndex)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)jenv->GetStringUTFChars(jarg3, 0);
    if (!arg3) return ;
  }
  arg4 = *(size_t **)&jarg4;
  if (!arg4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "size_t & reference is null");
    return ;
  } 
  arg5 = (size_t)jarg5; 
  (arg1)->read(arg2,arg3,*arg4,arg5);
  if (arg3) jenv->ReleaseStringUTFChars(jarg3, (const char *)arg3);
}


SWIGEXPORT void JNICALL Java_de_tubs_ibr_dtn_swig_swigJNI_NativeSession_1read_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jstring jarg3, jlong jarg4) {
  dtn::api::NativeSession *arg1 = (dtn::api::NativeSession *) 0 ;
  dtn::api::NativeSession::RegisterIndex arg2 ;
  char *arg3 = (char *) 0 ;
  size_t *arg4 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dtn::api::NativeSession **)&jarg1; 
  arg2 = (dtn::api::NativeSession::RegisterIndex)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)jenv->GetStringUTFChars(jarg3, 0);
    if (!arg3) return ;
  }
  arg4 = *(size_t **)&jarg4;
  if (!arg4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "size_t & reference is null");
    return ;
  } 
  (arg1)->read(arg2,arg3,*arg4);
  if (arg3) jenv->ReleaseStringUTFChars(jarg3, (const char *)arg3);
}


#ifdef __cplusplus
}
#endif

