/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_tubs_ibr_dtn_service_NativeDaemonWrapper */

#ifndef _Included_de_tubs_ibr_dtn_service_NativeDaemonWrapper
#define _Included_de_tubs_ibr_dtn_service_NativeDaemonWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_tubs_ibr_dtn_service_NativeDaemonWrapper
 * Method:    daemonInitialize
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_de_tubs_ibr_dtn_service_NativeDaemonWrapper_daemonInitialize
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     de_tubs_ibr_dtn_service_NativeDaemonWrapper
 * Method:    daemonMainLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tubs_ibr_dtn_service_NativeDaemonWrapper_daemonMainLoop
  (JNIEnv *, jclass);

/*
 * Class:     de_tubs_ibr_dtn_service_NativeDaemonWrapper
 * Method:    daemonShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tubs_ibr_dtn_service_NativeDaemonWrapper_daemonShutdown
  (JNIEnv *, jclass);

/*
 * Class:     de_tubs_ibr_dtn_service_NativeDaemonWrapper
 * Method:    getNeighbors
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_de_tubs_ibr_dtn_service_NativeDaemonWrapper_getNeighbors
  (JNIEnv *, jclass);

/*
 * Class:     de_tubs_ibr_dtn_service_NativeDaemonWrapper
 * Method:    addConnection
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_tubs_ibr_dtn_service_NativeDaemonWrapper_addConnection
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     de_tubs_ibr_dtn_service_NativeDaemonWrapper
 * Method:    removeConnection
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_tubs_ibr_dtn_service_NativeDaemonWrapper_removeConnection
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     de_tubs_ibr_dtn_service_NativeDaemonWrapper
 * Method:    setEndpoint
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_tubs_ibr_dtn_service_NativeDaemonWrapper_setEndpoint
  (JNIEnv *, jclass, jstring);

/*
 * Class:     de_tubs_ibr_dtn_service_NativeDaemonWrapper
 * Method:    addRegistration
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_tubs_ibr_dtn_service_NativeDaemonWrapper_addRegistration
  (JNIEnv *, jclass, jstring);

/*
 * Class:     de_tubs_ibr_dtn_service_NativeDaemonWrapper
 * Method:    loadBundle
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_tubs_ibr_dtn_service_NativeDaemonWrapper_loadBundle
  (JNIEnv *, jclass, jstring);

/*
 * Class:     de_tubs_ibr_dtn_service_NativeDaemonWrapper
 * Method:    getBundle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tubs_ibr_dtn_service_NativeDaemonWrapper_getBundle
  (JNIEnv *, jclass);

/*
 * Class:     de_tubs_ibr_dtn_service_NativeDaemonWrapper
 * Method:    loadAndGetBundle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tubs_ibr_dtn_service_NativeDaemonWrapper_loadAndGetBundle
  (JNIEnv *, jclass);

/*
 * Class:     de_tubs_ibr_dtn_service_NativeDaemonWrapper
 * Method:    markDelivered
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_tubs_ibr_dtn_service_NativeDaemonWrapper_markDelivered
  (JNIEnv *, jclass, jstring);

/*
 * Class:     de_tubs_ibr_dtn_service_NativeDaemonWrapper
 * Method:    send
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_de_tubs_ibr_dtn_service_NativeDaemonWrapper_send
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
